### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by terehov** [wmbenedetto/turbine.js#12]
Hi Warren, 

I really love your ideas behind turbine.js and would like to use it in production. 
Would you recommend me to do so? 
How would you describe the state of your development? Still active? Do you need any help? Or would you consider it to be finish? I really would like to know how you feel about this library and if you would recommend me to use it in production? 

One more question: What happens it my node-app craches. Is there a way to restart all the running workflow? Do I have to save them somewhere? 

Thank you very much :-)

**Comment by wmbenedetto** [comment]
The master branch is stable and has been used in production apps with no problems. There are additional features in the develop branch, but I haven't had a chance to write new unit tests for them yet, so I haven't moved them to master. Also, I'd like to move the unit tests to a more modern test framework (they're written with JS Test Driver, but that is pretty old school nowadays).

Beyond the features in develop and the unit tests, I don't have any immediate plans for additional features. It's pretty complete right now. I'm certainly open to suggestions and feature requests though. I'm sure there are things I haven't thought of.

I'm not exactly sure how your node app works or how you plan on using Turbine, so it's hard to say how you could "restart" the workflow. If the functions bound to your queries are referencing something that is maintaining your state, then this should theoretically be possible.
